GET http://localhost:3000/products

###

GET http://localhost:3000/products?page=2&limit=5&sort=asc


###
POST http://localhost:3000/login?type=admin
Content-Type: application/json

{
  "email": "barose_yongin@naver.com",
  "password": "whdkdyddlwhdkdyd@031"
}

###
GET http://localhost:3000/products/678dc0db32cd3ec3ff32c259

